In [1]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [2]:
a[1,3]

np.int64(8)

this isn't usual for python arrays

In [3]:
a.ndim

2

In [4]:
a.shape

(3, 4)

row/column, etc

In [5]:
a.size

12

In [6]:
a.dtype

dtype('int64')

In [9]:
print(np.zeros(4))
print(np.ones(4))
print(np.empty(4))
print(np.empty(4).dtype)

[0. 0. 0. 0.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
float64


In [10]:
np.arange(12, 24, 0.5)

array([12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5,
       23. , 23.5])

In [11]:
np.linspace(20, 40, num=100)

array([20.        , 20.2020202 , 20.4040404 , 20.60606061, 20.80808081,
       21.01010101, 21.21212121, 21.41414141, 21.61616162, 21.81818182,
       22.02020202, 22.22222222, 22.42424242, 22.62626263, 22.82828283,
       23.03030303, 23.23232323, 23.43434343, 23.63636364, 23.83838384,
       24.04040404, 24.24242424, 24.44444444, 24.64646465, 24.84848485,
       25.05050505, 25.25252525, 25.45454545, 25.65656566, 25.85858586,
       26.06060606, 26.26262626, 26.46464646, 26.66666667, 26.86868687,
       27.07070707, 27.27272727, 27.47474747, 27.67676768, 27.87878788,
       28.08080808, 28.28282828, 28.48484848, 28.68686869, 28.88888889,
       29.09090909, 29.29292929, 29.49494949, 29.6969697 , 29.8989899 ,
       30.1010101 , 30.3030303 , 30.50505051, 30.70707071, 30.90909091,
       31.11111111, 31.31313131, 31.51515152, 31.71717172, 31.91919192,
       32.12121212, 32.32323232, 32.52525253, 32.72727273, 32.92929293,
       33.13131313, 33.33333333, 33.53535354, 33.73737374, 33.93

In [13]:
print(np.arange(20, 40, dtype=np.int64))
print(np.arange(20, 40, dtype=np.int64).dtype)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
int64


In [14]:
print(np.sort(np.arange(40, 20, -1, dtype=np.int64)))

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [15]:
a.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])